### ISSUE TITLE
HTML page does not get updated on rebuild

### ISSUE THREAD

**Issue by chmue** [LSE-Methodology/MY451#5]
Discovered by @jacksojp 

The CI build succeeds ([see last build](https://travis-ci.com/LSE-Methodology/MY451/builds/55470642)), the PDF is updated to the new version but the changes are not reflected in the web version.

**Comment by chmue** [comment]
Although there seems to be some issue with the Travis configuration file ([see here](https://travis-ci.com/LSE-Methodology/MY451/requests)), the changes are actually pushed to the `gh-pages` branch, [e.g. here](https://github.com/LSE-Methodology/MY451/commit/4e7071197f9630ad41c3c307b08709abe5125aeb).

The problem might arise because most modern browsers aggressively cache pages. That is, the updated version is not actually downloaded but the old version is retrieved from the cache. Another possible explanation is that the updates take some time to be passed through GH Pages' content delivery network. I think the former is much more likely though.

@jacksojp Could you look at the page right now and verify that the updates you made yesterday, change academic year and lecturers among other things, are now reflected on the website?

The changes do actually show up for me now.

**Comment by jacksojp** [comment]
Yes, the page looks good. Has done all day. Slightly weird placement of the logo in the pdf version, but apart from that, it’s fine.

On 27 Sep 2017, at 18:11, Christian Mueller <notifications@github.com<mailto:notifications@github.com>> wrote:


Although there seems to be some issue with the Travis configuration file (see here<https://travis-ci.com/LSE-Methodology/MY451/requests>), the changes are actually pushed to the gh-pages branch, e.g. here<https://github.com/LSE-Methodology/MY451/commit/4e7071197f9630ad41c3c307b08709abe5125aeb>.

The problem might arise because most modern browsers aggressively cache pages. That is, the updated version is not actually downloaded but the old version is retrieved from the cache. Another possible explanation is that the updates take some time to be passed through GH Pages' content delivery network. I think the former is much more likely though.

@jacksojp<https://github.com/jacksojp> Could you look at the page right now and verify that the updates you made yesterday, change academic year and lecturers among other things, are now reflected on the website?

**Comment by chmue** [comment]
Ok, great! Thank you for the info.

FYI: I stumbled on this way to refresh the page and ignore the cache totally by chance today. Depending on your browser you can hit `ctrl+f5` or `shift+f5` to force a full, non-cached reload of the page.

**Comment by chmue** [comment]
I fixed the placement of the logo in b5fb1c96fae5dac0cb589328b73e42dad32f7fe2
